[programs.localnet]
token_sale = "BiymXGf4mxyYjDWfBAteLZq6ocgJz9HwPdUz3VRYMmnF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/token-sale.ts"
